;; lab06-test.lisp
;; lab06-test.lisp

(deftest test-next-state ()
    (check
      (equal (let ((std  '((1 . 2) (2 . (3 4)) (3 . nil) (4 . nil))))
	       (next-state std 2))
	     '(3 4))
      (equal (let ((std  '((1 . 2) (2 . (3 4)) (3 . nil) (4 . nil))))
	       (next-state std 1))
	     2)
      (equal (let ((std  '((1 . 2) (2 . (3 4)) (3 . nil) (4 . nil))))
	       (next-state std 3))
	     nil)
      (equal (let ((std  '((start . test1)    
                           (test1 . (init end1))
                           (init . test2)
                           (test2 . (bdy return))
                           (bdy . incr)
                           (incr . test2)
                           (return . end1)
                           (end1 . nil))))
	       (next-state std 'init))
	     'test2)))

(deftest test-jump-state ()
    (check
      (equal (let ((std '((start . test1)    
			  (test1 . (init end1))
			  (init . test2)
			  (test2 . (bdy return))
			  (bdy . incr)
			  (incr . test2)
			  (return . end1)
			  (end1 . nil))))
	       (jump-state std 'init 'test1))
	     'test2)
      (equal (let ((std '((start . test1)    
			  (test1 . (init end1))
			  (init . test2)
			  (test2 . (bdy return))
			  (bdy . incr)
			  (incr . test2)
			  (return . end1)
			  (end1 . nil))))
	       (jump-state std 'test2 'incr))
	     '(bdy return))
       (equal (let ((std '((start . test1)    
			  (test1 . (init end1))
			  (init . test2)
			  (test2 . (bdy return))
			  (bdy . incr)
			  (incr . test2)
			  (return . end1)
			  (end1 . nil))))
		(jump-state std nil 'return))
	      'return)
      (equal (let ((std '((1 . 2)    
			  (2 . (3 4))
			  (3 . nil)
			  (4 . nil))))
	       (jump-state std 3 2))
	     2)))

(deftest test-next-fork ()
  (check
    (equal (let ((std '((1 . 2)    
			(2 . (3 4))
			(3 . nil)
			(4 . nil))))
	     (next-fork std 1))
	   '(3 4))
    (equal (let ((std '((1 . 2)    
			(2 . (3 4))
			(3 . nil)
			(4 . nil))))
	     (next-fork std 3))
	   nil)
    (equal (let ((std '((1 . 2)    
			(2 . (3 4))
			(3 . 1)
			(4 . nil))))
	     (next-fork std 3))
	   '(3 4))
    (equal (let ((std '((start . test1)    
			(test1 . (init end1))
			(init . test2)
			(test2 . (bdy return))
			(bdy . incr)
			(incr . test2)
			(return . end1)
			(end1 . nil))))
	     (next-fork std 'bdy))
	   '(bdy return))))
  
(deftest test-interleave ()
  (check
    (equal (interleave '(a) '(d e f)) '(A D E F))
    (equal (interleave '(1 (2 3) 4) '(a b c d)) '(1 a (2 3) b 4 c d))
    (equal (interleave '() '()) ())
    (equal (interleave '(1 2) ()) '(1 2))
    (equal (interleave '(1 2 3) '(4)) '(1 4 2 3))))

(deftest test-comb ()
  (check
    (not (comb -10 2))
    (not (comb 3 5))
    (eql (comb 5 3) 10)
    (eql (comb 5 5) 1)
    (eql (comb 30 2) 435)))


			 
(defun test-lab06 ()
  (test-comb)
  (test-interleave)
  (test-next-fork)
  (test-jump-state)
  (test-next-state))

(test-lab06)
